Repository embention/RTD_core, pull requests merged in 2023-09, with the labels that each got.

#14 embention/RTD#161 Text style for side bar changed
  _static/custom.css
Labels: Code, Commit, Short, Odoo

#15 embention/RTD#169 Changed Sphinx version to 4.0.1
  requirements.txt
  sphinx_press_custom/setup.py
Labels: Analysis, Comment, PR, Odoo, Other PR

#16 embention/RTD#178 Bar side for manuals with single page
  _static/custom.css
Labels: Code, Commit, Odoo

#17 embention/IT#183 Library added
  requirements.txt
Labels: Code, Commit, Odoo

#18 embention/IT#183 urllib3 is used with windows
  requirements.txt
Labels: Code, Commit, Odoo
