Repository embention/RTD_core, pull requests merged in 2023-11, with the labels that each got.

#20 embention/RTD#186 New index level and index style changed
  _static/custom.css
Labels: Code, Commit, Odoo

#21 Automatic pull request
  .github/ISSUE_TEMPLATE/problem-report.md
Labels: Analysis, CM, Comment, IT

#22 Automatic pull request
  .github/workflows/add_issue_to_project.yml
Labels: Analysis, CM, Commit

#23 Automatic pull request
  .github/workflows/add_issue_to_project.yml
Labels: Analysis, CM, Commit
